### ISSUE TITLE
foldcolumns background

### ISSUE THREAD

**Issue by Cretezy** [Yazeed1s/oh-lucy.nvim#5]
<img width="93" alt="image" src="https://user-images.githubusercontent.com/2672503/200399089-3551d5a4-c3ed-42c9-8a89-eb1e053860e3.png">

foldcolumns don't match with rest of the theme. Otherwise looks great!

**Comment by yazeed1s** [comment]
Hey @Cretezy, the foldcolumn should be matched with the background now.
