### ISSUE TITLE
[Request] Plugin Support with Diffview.nvim

### ISSUE THREAD

**Issue by MikePresman** [Yazeed1s/oh-lucy.nvim#7]
https://github.com/sindrets/diffview.nvim

If you could support or explain how to change the colors for the above plugin it'd be really appreciated. I don't have much I'm picky about except it'd be nice if the colors were red or green like in the screenshot (currently it is blue and pink and red).

Awesome colorscheme btw ! I'll be using it for a while

**Comment by yazeed1s** [comment]
Hey @MikePresman, i was able to trace the issue, it seems like the background color for diff changes, adds, removes, etc is not specified, therfore, it defaults to bright blue, red, pink. 
```
    DiffAdd     = { fg = colors.green_func },
    DiffAdded   = { fg = colors.green_func },
    DiffChange  = { fg = colors.green_func },
    DiffDelete  = { fg = colors.red_key_w },
    DiffRemoved = { fg = colors.red_key_w },
    -- bg(background) should be added like...  
    DiffAdd     = { fg = colors.green_func, bg = colors.green_diff },
    -- the rest 
```

However, the issue still resist even after adding bgs, i may need to implement some helper function to calculate the needed color transparency (hex values alone won't work). i will fix this over the weekend!

**Comment by MikePresman** [comment]
Thanks so much for taking the time to do this !

**Comment by MikePresman** [comment]
Closing cause stale
